services:
  samba:
    container_name: samba
    image: dockurr/samba:4.21.6
    volumes:
      - /mnt/data/backup:/storage
      - /var/log/samba:/var/log/samba
      - /var/cache/samba:/var/cache/samba
      - /run/samba:/run/samba
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    network_mode: "host"
    restart: always
    environment:
      - USER=debian
      - PASS=1231
      - UID=1000
      - GID=1000
    deploy:
      resources:
        limits:
          memory: 2048M
