version: '3.9'

services:
  samba:
    container_name: samba
    image: registry-docker.cloud.lab/dperson/samba
    volumes:
      - /data/backup:/mount
      - /var/log/samba:/var/log/samba
      - /var/cache/samba:/var/cache/samba
      - /run/samba:/run/samba
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    network_mode: "host"
    restart: always
    environment:
      - USER=debian;1231
      - USERID=1000
      - GROUPID=1000
      - SHARE=share;/mount/;yes;no;no;all;none
    deploy:
      resources:
        limits:
          memory: 512M
