version: '3.9'

services:
  bind9:
    container_name: bind9
    image: 10.200.101.20:8083/ubuntu/bind9:9.18-22.04_beta
    environment:
      BIND9_USER: bind
      TZ: Asia/Shanghai
    volumes:
      - ./etc/bind/named.conf:/etc/bind/named.conf
      - var_cache_bind_vol:/var/cache/bind
      - var_lib_bind_vol:/var/lib/bind
    network_mode: "host"
    deploy:
      resources:
        limits:
          memory: 4096M

volumes:
  var_cache_bind_vol:
  var_lib_bind_vol:
