version: '3.9'

services:
  grafana:
    container_name: grafana
    image: registry-docker.cloud.lab/grafana/grafana-oss
    volumes:
      - /docker/var/lib/grafana:/var/lib/grafana
      - /docker/var/log/grafana:/var/log/grafana
    network_mode: "host"
    deploy:
      resources:
        limits:
          memory: 4096M
