version: '3.9'

services:
  gitlab:
    container_name: gitlab
    image: registry-docker.cloud.lab/gitlab/gitlab-ce:latest
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.cloud.lab'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    volumes:
      - /etc/gitlab:/etc/gitlab
      - /var/log/gitlab:/var/log/gitlab
      - /var/opt/gitlab:/var/opt/gitlab
    shm_size: '256m'
    network_mode: "host"
    deploy:
      resources:
        limits:
          memory: 4096M
