version: '3.9'

services:
  squid:
    container_name: squid
    image: registry-docker.cloud.lab/ubuntu/squid:5.2-22.04_beta
    volumes:
      - /data/squid/etc/squid.conf:/etc/squid/squid.conf
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      - /var/log/squid:/var/log/squid
      - var_spool_squid_vol:/var/spool/squid
    network_mode: "host"
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M

volumes:
  var_spool_squid_vol:
