version: '2.4'

services:
  squid:
    container_name: squid
    image: 10.200.101.20:8083/ubuntu/squid:5.2-22.04_beta
    mem_limit: 4096m
    volumes:
      - /data/squid/etc/squid.conf:/etc/squid/squid.conf
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      - /var/log/squid:/var/log/squid
      - /var/spool/squid:/var/spool/squid
    network_mode: "host"
    restart: always
    privileged: true
