services:
  freeipa:
    container_name: freeipa
    image: registry.cloud.lab/freeipa/freeipa-server:rocky-9-4.11.0
    volumes:
      - /data/freeipa-data:/data:Z
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    network_mode: "host"
    restart: always
    environment:
      - IPA_SERVER_HOSTNAME=vm-data-20.cloud.lab
    deploy:
      resources:
        limits:
          memory: 4096M
