services:
  nginx:
    container_name: nginx
    image: registry.cloud.lab/nginx
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/ssl/cert.crt:/etc/nginx/ssl/cert.crt
      - ./etc/nginx/ssl/cert.key:/etc/nginx/ssl/cert.key
    network_mode: "host"
