version: '2.4'

services:
  nginx:
    container_name: nginx
    image: 10.200.101.20:8083/nginx
    mem_limit: 1024m
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/ssl/cert.crt:/etc/nginx/ssl/cert.crt
      - ./etc/nginx/ssl/cert.key:/etc/nginx/ssl/cert.key
    network_mode: "host"
    restart: always
