version: '3.9'

services:
  nexus3:
    container_name: nexus3
    image: 10.200.101.20:8083/sonatype/nexus3:3.51.0
    volumes:
      - /data/nexus-data:/nexus-data
    ports:
      - "0.0.0.0:8081:8081"
      - "0.0.0.0:8082:8082"
      - "0.0.0.0:8083:8083"
      - "0.0.0.0:8084:8084"
    deploy:
      resources:
        limits:
          memory: 4096M
