services:
  ntp:
    image: dockurr/chrony:4.7
    container_name: ntp
    environment:
      NTP_SERVERS: "ntp1.aliyun.com,ntp2.aliyun.com,ntp3.aliyun.com,ntp4.aliyun.com"
      TZ: "Asia/Shanghai"
    networks:
      - net
    ports:
      - 123:123/udp
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M

networks:
  net:
    driver: bridge
