version: '3.9'

services:
  portainer:
    container_name: portainer
    image: registry-docker.cloud.lab/portainer/portainer-ce:2.19.0
    volumes:
      - /data/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: "host"
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
