version: '3.9'

services:
  portainer:
    container_name: portainer
    image: 10.200.101.20:8083/portainer/portainer-ce:2.17.1
    volumes:
      - /data/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: "host"
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
