version: '2.4'
services:
  postgres:
    container_name: postgres
    image: 10.200.101.20:8083/postgres:15
    mem_limit: 4096m
    environment:
      POSTGRES_PASSWORD: admin123
    volumes:
      - /docker/postgresql/data:/var/lib/postgresql/data
    network_mode: "host"
    restart: always
  adminer:
    container_name: adminer
    image: 10.200.101.20:8083/adminer
    network_mode: "host"
    restart: always
  portainer:
    container_name: portainer
    image: 10.200.101.20:8083/portainer/portainer-ce:linux-amd64-2.15.1
    mem_limit: 4096m
    volumes:
      - /docker/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: "host"
    restart: always
    privileged: true
