services:
  postgres:
    container_name: postgres
    image: registry.cloud.lab/postgres:15
    environment:
      POSTGRES_PASSWORD: admin123
    volumes:
      - /docker/var/lib/postgresql/data:/var/lib/postgresql/data
    network_mode: "host"
    deploy:
      resources:
        limits:
          memory: 4096M
  adminer:
    container_name: adminer
    image: registry.cloud.lab/adminer:4
    network_mode: "host"
  nginx:
    container_name: nginx
    image: registry.cloud.lab/nginx:1.26
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/ssl/cert.crt:/etc/nginx/ssl/cert.crt
      - ./etc/nginx/ssl/cert.key:/etc/nginx/ssl/cert.key
    network_mode: "host"
