version: '2.4'

services:
  postgres:
    container_name: postgres
    image: 10.200.101.20:8083/postgres:15
    mem_limit: 4096m
    environment:
      POSTGRES_PASSWORD: admin123
    volumes:
      - /docker/var/lib/postgresql/data:/var/lib/postgresql/data
    network_mode: "host"
    restart: always
  adminer:
    container_name: adminer
    image: 10.200.101.20:8083/adminer
    mem_limit: 1024m
    network_mode: "host"
    restart: always
  nginx:
    container_name: nginx
    image: 10.200.101.20:8083/nginx
    mem_limit: 1024m
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/ssl/cert.crt:/etc/nginx/ssl/cert.crt
      - ./etc/nginx/ssl/cert.key:/etc/nginx/ssl/cert.key
    network_mode: "host"
    restart: always
